### ISSUE TITLE
RoomE Home Page Inconsistencies 

### ISSUE THREAD

**Issue by toopz** [ryansl/RoomE#10]
1. When switching from the RoomE home page, to the login tab, or any other tab. There is a small shift in where the RoomE logo and all other tabs are displayed. Only happens when full screen though. If window is forced to half screen size this doesn't happen.
2. Switching between tabs, login -> search, causes a screen shift as well.
3. About us tab seems to be zoomed in relative to rest
4. Can we also make them all have a uniform background? It seems odd to have a beautiful picture and then go to a dull grey background. 
5. Also using firefox, the About Us page does not have our first letter highlighted in red. Can we also give the pictures a larger padding so the text does not start immediately at the image.

6. Switching tabs also causes a screen shift when going from 'Logged Out' notice to other tabs.

Screen shift seems to be due to the addition of the right hand scroll bar. Don't know how unavoidable that is...

**Comment by ryansl** [comment]
Done
