### ISSUE TITLE
To-Do List Priority

### ISSUE THREAD

**Issue by kathleen-flynn** [ryansl/RoomE#14]
Update form field description to say "Priority - from 1 to 10 (1=lowest and 10=highest)." 
Remove the percentages from the to-do list.

**Comment by toopz** [comment]
I think priority should be its own column. It looks awkward to have it with the description. Also would it be possible to unassign yourself to a task, perhaps by reclicking your name?

**Comment by connection-lost** [comment]
Fixing:
1. priority have separate column
2. Unassign myself

**Comment by connection-lost** [comment]
Done
