### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by toopz** [ryansl/RoomE#9]
1. There are links for both viewing and modifying the To-Do list on the dashboard. Both take you to the same page, remove redundancy.

2. To-Do list should have a separate column for priority if possible. Also is it possible to have a smaller priorty range? Perhaps 1-5 or just actual words such as low, medium, high, urgent?

3. Can unassigned items be listed as 'Unassigned' instead of 'Unknown?'

**Comment by ryansl** [comment]
Done. Priority is 1-10.
